### POST request to create a new patient
POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Berkay Yets",
  "email": "tatawa5134@example.com",
  "registeredDate": "2025-11-04",
  "address": "1234 main street",
  "dateOfBirth": "1995-01-01"
}